name: giselleherrera
favicon: null
layout_spectrum: 0.9502749184612185
typography_spectrum: 0.5331024986226112
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.1277486828621477
  lightness: 0.7648987520951778
  saturation: 0.6100788114126772
  rhythmicContrast: 0.8121076833922416
purpose: []
